// old_app/vici-prediction-market-application/frontend/src/components/Header.tsx
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuTrigger
} from '@/components/ui/dropdown-menu';
import { useQueryClient } from '@tanstack/react-query';
import { LogOut, Menu, Shield, User, Wallet, X, Zap } from 'lucide-react';
import { useState } from 'react';
import type { Page } from '../App';
import { useInternetIdentity } from '../hooks/useInternetIdentity';
import { useGetCallerUserProfile, useIsCallerAdmin } from '../hooks/useQueries';

interface HeaderProps {
	currentPage: Page;
	onNavigate: (page: Page) => void;
}

export default function Header({ currentPage, onNavigate }: HeaderProps) {
	const { login, clear, loginStatus, identity } = useInternetIdentity();
	const { data: userProfile } = useGetCallerUserProfile();
	const { data: isAdmin } = useIsCallerAdmin();
	const queryClient = useQueryClient();
	const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

	const isAuthenticated = !!identity;
	const disabled = loginStatus === 'logging-in';

	const handleAuth = async () => {
		if (isAuthenticated) {
			await clear();
			queryClient.clear();
			onNavigate('home');
		} else {
			try {
				await login();
			} catch (error: any) {
				console.error('Login error:', error);
				if (error.message === 'User is already authenticated') {
					await clear();
					setTimeout(() => login(), 300);
				}
			}
		}
	};

	const navItems: { label: string; page: Page; authRequired?: boolean; icon?: React.ReactNode }[] =
		[
			{ label: 'Home', page: 'home' },
			{ label: 'Markets', page: 'markets' },
			{ label: 'Rush', page: 'rush', authRequired: true, icon: <Zap className="h-4 w-4" /> },
			{ label: 'Portfolio', page: 'portfolio', authRequired: true },
			{ label: 'Wallet', page: 'wallet', authRequired: true, icon: <Wallet className="h-4 w-4" /> },
			{ label: 'Leaderboard', page: 'leaderboard' },
			{ label: 'Learn', page: 'learn' }
		];

	return (
		<header className="sticky top-0 z-50 w-full border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
			<div className="container mx-auto px-4">
				<div className="flex h-16 items-center justify-between">
					{/* Logo */}
					<button
						onClick={() => onNavigate('home')}
						className="flex items-center space-x-2 hover:opacity-80 transition-opacity"
					>
						<img
							src="/assets/vici-coin-logo-transparent.dim_200x200.png"
							alt="Vici"
							className="h-8 w-8"
						/>
						<span className="text-xl font-bold text-primary">Vici</span>
					</button>

					{/* Desktop Navigation */}
					<nav className="hidden md:flex items-center space-x-1">
						{navItems.map((item) => {
							if (item.authRequired && !isAuthenticated) return null;
							return (
								<Button
									key={item.page}
									variant={currentPage === item.page ? 'default' : 'ghost'}
									onClick={() => onNavigate(item.page)}
									className="flex items-center gap-2"
								>
									{item.icon}
									{item.label}
								</Button>
							);
						})}
						{isAdmin && (
							<Button
								variant={currentPage === 'admin' ? 'default' : 'ghost'}
								onClick={() => onNavigate('admin')}
							>
								<Shield className="h-4 w-4 mr-2" />
								Admin
							</Button>
						)}
					</nav>

					{/* User Section */}
					<div className="flex items-center space-x-4">
						{isAuthenticated && userProfile && (
							<div className="hidden md:flex items-center space-x-2 px-3 py-1.5 rounded-full bg-primary/10 text-primary font-semibold">
								<span className="text-lg">Ꝟ</span>
								<span>{Number(userProfile.balance).toLocaleString()}</span>
							</div>
						)}

						{isAuthenticated ? (
							<DropdownMenu>
								<DropdownMenuTrigger asChild>
									<Button variant="ghost" className="relative h-10 w-10 rounded-full">
										<Avatar className="h-10 w-10">
											<AvatarImage src={userProfile?.avatar} alt={userProfile?.nickname} />
											<AvatarFallback>
												{userProfile?.nickname?.charAt(0).toUpperCase() || 'U'}
											</AvatarFallback>
										</Avatar>
									</Button>
								</DropdownMenuTrigger>
								<DropdownMenuContent align="end" className="w-56">
									<DropdownMenuItem onClick={() => onNavigate('profile')}>
										<User className="mr-2 h-4 w-4" />
										Profile
									</DropdownMenuItem>
									<DropdownMenuItem onClick={handleAuth}>
										<LogOut className="mr-2 h-4 w-4" />
										Logout
									</DropdownMenuItem>
								</DropdownMenuContent>
							</DropdownMenu>
						) : (
							<Button onClick={handleAuth} disabled={disabled}>
								{disabled ? 'Connecting...' : 'Login'}
							</Button>
						)}

						{/* Mobile Menu Button */}
						<Button
							variant="ghost"
							size="icon"
							className="md:hidden"
							onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
						>
							{mobileMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
						</Button>
					</div>
				</div>

				{/* Mobile Navigation */}
				{mobileMenuOpen && (
					<nav className="md:hidden py-4 space-y-2 border-t border-border">
						{navItems.map((item) => {
							if (item.authRequired && !isAuthenticated) return null;
							return (
								<Button
									key={item.page}
									variant={currentPage === item.page ? 'default' : 'ghost'}
									onClick={() => {
										onNavigate(item.page);
										setMobileMenuOpen(false);
									}}
									className="w-full justify-start flex items-center gap-2"
								>
									{item.icon}
									{item.label}
								</Button>
							);
						})}
						{isAdmin && (
							<Button
								variant={currentPage === 'admin' ? 'default' : 'ghost'}
								onClick={() => {
									onNavigate('admin');
									setMobileMenuOpen(false);
								}}
								className="w-full justify-start"
							>
								<Shield className="h-4 w-4 mr-2" />
								Admin
							</Button>
						)}
						{isAuthenticated && userProfile && (
							<div className="flex items-center justify-center space-x-2 px-3 py-2 rounded-full bg-primary/10 text-primary font-semibold">
								<span className="text-lg">Ꝟ</span>
								<span>{Number(userProfile.balance).toLocaleString()}</span>
							</div>
						)}
					</nav>
				)}
			</div>
		</header>
	);
}

// old/frontend/src/components/Header.svelte
<script lang="ts">
	import { auth, isAuthenticated, loginStatus } from '../stores/auth';
	import { userProfile, isAdmin } from '../stores/profile';
	import Button from './ui/Button.svelte';
	import Avatar from './ui/Avatar.svelte';
	import { Menu, X, User, LogOut, Shield, Zap, Wallet } from 'lucide-svelte';
	import { cn } from '../lib/utils';

	export let currentPage: string;
	export let onNavigate: (page: string) => void;

	let mobileMenuOpen = false;
	let dropdownOpen = false;

	$: disabled = $loginStatus === 'logging-in';

	const handleAuth = async () => {
		if ($isAuthenticated) {
			await auth.clear();
			onNavigate('home');
		} else {
			try {
				await auth.login();
			} catch (error) {
				console.error('Login error:', error);
			}
		}
	};

	const navItems = [
		{ label: 'Home', page: 'home' },
		{ label: 'Markets', page: 'markets' },
		{ label: 'Rush', page: 'rush', authRequired: true, icon: Zap },
		{ label: 'Portfolio', page: 'portfolio', authRequired: true },
		{ label: 'Wallet', page: 'wallet', authRequired: true, icon: Wallet },
		{ label: 'Leaderboard', page: 'leaderboard' },
		{ label: 'Learn', page: 'learn' }
	];
</script>

<header
	class="border-border bg-background/95 supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50 w-full border-b backdrop-blur"
>
	<div class="container mx-auto px-4">
		<div class="flex h-16 items-center justify-between">
			<!-- Logo -->
			<button
				on:click={() => onNavigate('home')}
				class="flex items-center space-x-2 transition-opacity hover:opacity-80"
			>
				<img src="/assets/vici-coin-logo-transparent.dim_200x200.png" alt="Vici" class="h-8 w-8" />
				<span class="text-primary text-xl font-bold">Vici</span>
			</button>

			<!-- Desktop Navigation -->
			<nav class="hidden items-center space-x-1 md:flex">
				{#each navItems as item}
					{#if !item.authRequired || $isAuthenticated}
						<Button
							variant={currentPage === item.page ? 'default' : 'ghost'}
							on:click={() => onNavigate(item.page)}
							className="flex items-center gap-2"
						>
							{#if item.icon}
								<svelte:component this={item.icon} size={16} />
							{/if}
							{item.label}
						</Button>
					{/if}
				{/each}
				{#if $isAdmin}
					<Button
						variant={currentPage === 'admin' ? 'default' : 'ghost'}
						on:click={() => onNavigate('admin')}
						className="flex items-center gap-2"
					>
						<Shield size={16} />
						Admin
					</Button>
				{/if}
			</nav>

			<!-- User Section -->
			<div class="flex items-center space-x-4">
				{#if $isAuthenticated && $userProfile?.profile}
					<div
						class="bg-primary/10 text-primary hidden items-center space-x-2 rounded-full px-3 py-1.5 font-semibold md:flex"
					>
						<span class="text-lg">Ꝟ</span>
						<span>{Number($userProfile.profile.balance).toLocaleString()}</span>
					</div>
				{/if}

				{#if $isAuthenticated}
					<div class="relative">
						<button
							class="border-border relative h-10 w-10 overflow-hidden rounded-full border"
							on:click={() => (dropdownOpen = !dropdownOpen)}
						>
							<Avatar
								src={$userProfile?.profile?.avatar}
								alt={$userProfile?.profile?.nickname}
								fallback={$userProfile?.profile?.nickname?.charAt(0).toUpperCase() || 'U'}
							/>
						</button>

						{#if dropdownOpen}
							<div
								class="border-border bg-popover text-popover-foreground absolute right-0 z-50 mt-2 w-56 rounded-md border shadow-md"
							>
								<div class="py-1">
									<button
										class="hover:bg-accent hover:text-accent-foreground flex w-full items-center px-4 py-2 text-sm"
										on:click={() => {
											onNavigate('profile');
											dropdownOpen = false;
										}}
									>
										<User size={16} class="mr-2" />
										Profile
									</button>
									<button
										class="hover:bg-accent hover:text-accent-foreground text-destructive flex w-full items-center px-4 py-2 text-sm"
										on:click={() => {
											handleAuth();
											dropdownOpen = false;
										}}
									>
										<LogOut size={16} class="mr-2" />
										Logout
									</button>
								</div>
							</div>
							<!-- Click outside handler -->
							<div class="fixed inset-0 z-40" on:click={() => (dropdownOpen = false)}></div>
						{/if}
					</div>
				{:else}
					<Button on:click={handleAuth} {disabled}>
						{disabled ? 'Connecting...' : 'Login'}
					</Button>
				{/if}

				<!-- Mobile Menu Button -->
				<Button
					variant="ghost"
					size="icon"
					className="md:hidden"
					on:click={() => (mobileMenuOpen = !mobileMenuOpen)}
				>
					{#if mobileMenuOpen}
						<svelte:component this={X} size={24} />
					{:else}
						<svelte:component this={Menu} size={24} />
					{/if}
				</Button>
			</div>
		</div>

		<!-- Mobile Navigation -->
		{#if mobileMenuOpen}
			<nav class="border-border space-y-2 border-t py-4 md:hidden">
				{#each navItems as item}
					{#if !item.authRequired || $isAuthenticated}
						<Button
							variant={currentPage === item.page ? 'default' : 'ghost'}
							on:click={() => {
								onNavigate(item.page);
								mobileMenuOpen = false;
							}}
							className="w-full justify-start flex items-center gap-2"
						>
							{#if item.icon}
								<svelte:component this={item.icon} size={16} />
							{/if}
							{item.label}
						</Button>
					{/if}
				{/each}
				{#if $isAdmin}
					<Button
						variant={currentPage === 'admin' ? 'default' : 'ghost'}
						on:click={() => {
							onNavigate('admin');
							mobileMenuOpen = false;
						}}
						className="w-full justify-start"
					>
						<Shield size={16} class="mr-2" />
						Admin
					</Button>
				{/if}
				{#if $isAuthenticated && $userProfile?.profile}
					<div
						class="bg-primary/10 text-primary flex items-center justify-center space-x-2 rounded-full px-3 py-2 font-semibold"
					>
						<span class="text-lg">Ꝟ</span>
						<span>{Number($userProfile.profile.balance).toLocaleString()}</span>
					</div>
				{/if}
			</nav>
		{/if}
	</div>
</header>
