// old/frontend/src/pages/AdminPage.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { backend } from '../stores/actor';
	import { markets } from '../stores/markets';
	import { userProfile } from '../stores/profile';
	import { auth } from '../stores/auth';
	import Card from '../components/ui/Card.svelte';
	import Button from '../components/ui/Button.svelte';
	import Input from '../components/ui/Input.svelte';
	import Textarea from '../components/ui/Textarea.svelte';
	import Badge from '../components/ui/Badge.svelte';
	import Switch from '../components/ui/Switch.svelte';
	import RadioGroup from '../components/ui/RadioGroup.svelte';
	import RadioGroupItem from '../components/ui/RadioGroupItem.svelte';
	import {
		Plus,
		CheckCircle,
		Coins,
		Lock,
		AlertTriangle,
		Clock,
		Shield,
		Crown,
		Info,
		Loader2
	} from 'lucide-svelte';
	import { Principal } from '@icp-sdk/core/principal';
	import { toast } from 'sonner';

	// Tabs state
	let activeTab = 'resolve';

	// Create Market Form
	let title = '';
	let description = '';
	let categories = '';
	let expirationDate = '';
	let inviteOnly = false;
	let initialInvites = '';
	let isCreatingMarket = false;

	// Grant Coins Form (Placeholder)
	let userPrincipal = '';
	let coinAmount = '';

	// Admin Management (Placeholder)
	let adminList: Principal[] = [];
	let isAdminListLoading = false;
	let newAdminPrincipal = '';

	// Market Resolution State
	let selectedOutcomes: Record<string, string> = {};
	let isResolving: Record<string, boolean> = {};

	$: sortedMarkets = [...$markets.markets].sort((a, b) => {
		const now = BigInt(Date.now() * 1000000);
		const aExpired = a.expiration < now;
		const bExpired = b.expiration < now;
		const aResolved = a.status === 'resolved';
		const bResolved = b.status === 'resolved';

		if (aExpired && !aResolved && (!bExpired || bResolved)) return -1;
		if (bExpired && !bResolved && (!aExpired || aResolved)) return 1;

		return Number(a.expiration - b.expiration);
	});

	const isMarketExpired = (expiration: bigint): boolean => {
		return expiration < BigInt(Date.now() * 1000000);
	};

	const formatExpirationDate = (expiration: bigint): string => {
		return new Date(Number(expiration) / 1000000).toLocaleString();
	};

	const handleCreateMarket = async (e: Event) => {
		e.preventDefault();
		if (!title || !description || !expirationDate) {
			toast.error('Please fill in all required fields');
			return;
		}

		isCreatingMarket = true;
		try {
			const expiration = BigInt(new Date(expirationDate).getTime() * 1000000);
			const categoryArray = categories
				.split(',')
				.map((c) => c.trim())
				.filter(Boolean);

			let invitedUsersList: Principal[] = [];
			if (inviteOnly && initialInvites.trim()) {
				const invitePrincipals = initialInvites
					.split(',')
					.map((p) => p.trim())
					.filter(Boolean);
				invitedUsersList = invitePrincipals.map((p) => Principal.fromText(p));
			}

			const { actor } = $backend;
			if (!actor) throw new Error('Actor not available');

			await actor.createMarket(
				title,
				description,
				categoryArray,
				expiration,
				inviteOnly,
				invitedUsersList
			);

			toast.success('Market created successfully');
			title = '';
			description = '';
			categories = '';
			expirationDate = '';
			inviteOnly = false;
			initialInvites = '';
			markets.refresh();
		} catch (error: any) {
			toast.error(error.message || 'Failed to create market');
		} finally {
			isCreatingMarket = false;
		}
	};

	const handleResolveMarket = async (marketId: bigint) => {
		const outcome = selectedOutcomes[marketId.toString()];
		if (!outcome) return;

		if (outcome === 'canceled') {
			toast.error('CANCELED outcome is not yet supported');
			return;
		}

		isResolving[marketId.toString()] = true;
		try {
			const { actor } = $backend;
			if (!actor) throw new Error('Actor not available');

			await actor.resolveMarket(marketId, outcome === 'yes');
			toast.success(`Market resolved as ${outcome.toUpperCase()}`);

			delete selectedOutcomes[marketId.toString()];
			selectedOutcomes = selectedOutcomes; // Trigger reactivity
			markets.refresh();
			userProfile.refresh();
		} catch (error: any) {
			toast.error(error.message || 'Failed to resolve market');
		} finally {
			isResolving[marketId.toString()] = false;
		}
	};

	onMount(async () => {
		const { actor } = $backend;
		if (actor && 'getAdminList' in (actor as any)) {
			isAdminListLoading = true;
			try {
				adminList = await (actor as any).getAdminList();
			} catch (error) {
				console.error('Failed to fetch admin list:', error);
			} finally {
				isAdminListLoading = false;
			}
		}
	});

	const handleTabClick = (tab: string) => (activeTab = tab);
</script>

<div class="container mx-auto px-4 py-8">
	<div class="space-y-8">
		<!-- Header -->
		<div>
			<h1 class="text-foreground text-4xl font-bold">Admin Panel</h1>
			<p class="text-muted-foreground mt-2">Manage markets, users, and admins</p>
		</div>

		<!-- Tabs List -->
		<div class="border-border flex border-b">
			<button
				class="border-b-2 px-4 py-2 text-sm font-medium transition-colors {activeTab === 'resolve'
					? 'border-primary text-primary'
					: 'text-muted-foreground hover:text-foreground border-transparent'}"
				on:click={() => handleTabClick('resolve')}
			>
				Market Resolution
			</button>
			<button
				class="border-b-2 px-4 py-2 text-sm font-medium transition-colors {activeTab === 'create'
					? 'border-primary text-primary'
					: 'text-muted-foreground hover:text-foreground border-transparent'}"
				on:click={() => handleTabClick('create')}
			>
				Create Market
			</button>
			<button
				class="border-b-2 px-4 py-2 text-sm font-medium transition-colors {activeTab === 'grant'
					? 'border-primary text-primary'
					: 'text-muted-foreground hover:text-foreground border-transparent'}"
				on:click={() => handleTabClick('grant')}
			>
				Grant Coins
			</button>
			<button
				class="border-b-2 px-4 py-2 text-sm font-medium transition-colors {activeTab === 'admins'
					? 'border-primary text-primary'
					: 'text-muted-foreground hover:text-foreground border-transparent'}"
				on:click={() => handleTabClick('admins')}
			>
				Admin Management
			</button>
		</div>

		{#if activeTab === 'resolve'}
			<div class="space-y-6">
				<Card>
					<div class="p-6">
						<h3 class="mb-2 flex items-center gap-2 text-xl font-bold">
							<CheckCircle size={20} />
							Market Resolution Dashboard
						</h3>
						<p class="text-muted-foreground mb-6 text-sm">
							Resolve market outcomes. Expired markets requiring urgent attention are highlighted.
						</p>

						{#if sortedMarkets.length > 0}
							<div class="space-y-4">
								{#each sortedMarkets as market}
									{@const expired = isMarketExpired(market.expiration)}
									{@const resolved = market.status === 'resolved'}
									{@const urgent = expired && !resolved}
									{@const marketIdStr = market.id.toString()}
									{@const selectedOutcome = selectedOutcomes[marketIdStr]}

									<div
										class="rounded-lg border-2 p-4 transition-all {urgent
											? 'border-red-500 bg-red-50'
											: 'border-slate-100 bg-white shadow-sm'}"
									>
										{#if urgent}
											<div class="mb-3 flex items-center gap-2 text-red-600">
												<AlertTriangle size={20} />
												<span class="text-sm font-bold uppercase">Urgent: Expired & Unresolved</span
												>
											</div>
										{/if}

										<div class="space-y-3">
											<div class="flex justify-between gap-4">
												<div class="flex-1">
													<h4 class="text-lg font-bold">
														{market.title}
													</h4>
													<p class="text-muted-foreground mt-1 line-clamp-2 text-sm">
														{market.description}
													</p>
												</div>
											</div>

											<div class="flex flex-wrap items-center gap-2">
												<Badge
													variant={market.status === 'open'
														? 'default'
														: market.status === 'resolved'
															? 'success'
															: 'secondary'}
												>
													{market.status.toUpperCase()}
												</Badge>
												{#if market.inviteOnly}
													<Badge variant="outline" class="gap-1">
														<Lock size={12} /> Invite-only
													</Badge>
												{/if}
												<Badge variant={expired ? 'destructive' : 'outline'} class="gap-1">
													<Clock size={12} />
													{expired ? 'Expired' : 'Active'}
												</Badge>
												<span class="text-muted-foreground text-xs"
													>Expires: {formatExpirationDate(market.expiration)}</span
												>
											</div>

											{#if resolved}
												<div class="border-t pt-3">
													<div class="flex items-center gap-2">
														<span class="text-muted-foreground text-sm font-medium"
															>Resolved Outcome:</span
														>
														<Badge variant={market.resolvedOutcome ? 'success' : 'destructive'}>
															{market.resolvedOutcome ? 'YES' : 'NO'}
														</Badge>
													</div>
												</div>
											{:else}
												<div class="space-y-3 border-t pt-3">
													<label class="block text-sm font-medium">Select Outcome:</label>
													<RadioGroup
														value={selectedOutcome || ''}
														onValueChange={(v) => {
															selectedOutcomes[marketIdStr] = v;
															selectedOutcomes = selectedOutcomes;
														}}
														className="flex gap-6"
													>
														<div class="flex items-center gap-2">
															<RadioGroupItem value="yes" id="yes-{marketIdStr}" />
															<label for="yes-{marketIdStr}" class="cursor-pointer text-sm"
																>YES</label
															>
														</div>
														<div class="flex items-center gap-2">
															<RadioGroupItem value="no" id="no-{marketIdStr}" />
															<label for="no-{marketIdStr}" class="cursor-pointer text-sm">NO</label
															>
														</div>
														<div class="flex items-center gap-2">
															<RadioGroupItem value="canceled" id="canceled-{marketIdStr}" />
															<label
																for="canceled-{marketIdStr}"
																class="text-muted-foreground cursor-pointer text-sm">CANCELED</label
															>
														</div>
													</RadioGroup>

													<Button
														size="sm"
														on:click={() => handleResolveMarket(market.id)}
														disabled={!selectedOutcome || isResolving[marketIdStr]}
														class={urgent ? 'bg-red-600 text-white hover:bg-red-700' : ''}
													>
														{#if isResolving[marketIdStr]}
															<Loader2 size={16} class="mr-2 animate-spin" />
															Resolving...
														{:else}
															<CheckCircle size={16} class="mr-2" />
															Resolve Market
														{/if}
													</Button>
												</div>
											{/if}
										</div>
									</div>
								{/each}
							</div>
						{:else}
							<div class="text-muted-foreground py-12 text-center">
								<p>No markets available</p>
							</div>
						{/if}
					</div>
				</Card>
			</div>
		{:else if activeTab === 'create'}
			<Card>
				<div class="p-6">
					<h3 class="mb-6 flex items-center gap-2 text-xl font-bold">
						<Plus size={20} />
						Create New Market
					</h3>
					<form on:submit={handleCreateMarket} class="space-y-4">
						<div class="space-y-2">
							<label for="title" class="text-sm font-medium">Title *</label>
							<Input
								id="title"
								bind:value={title}
								placeholder="Will Bitcoin reach $100k?"
								required
							/>
						</div>
						<div class="space-y-2">
							<label for="description" class="text-sm font-medium">Description *</label>
							<Textarea
								id="description"
								bind:value={description}
								placeholder="Detailed resolution criteria..."
								rows={4}
								required
							/>
						</div>
						<div class="space-y-2">
							<label for="categories" class="text-sm font-medium"
								>Categories (comma-separated)</label
							>
							<Input id="categories" bind:value={categories} placeholder="Crypto, Finance" />
						</div>
						<div class="space-y-2">
							<label for="expiration" class="text-sm font-medium">Expiration Date *</label>
							<Input id="expiration" type="datetime-local" bind:value={expirationDate} required />
						</div>
						<div class="space-y-2">
							<div class="flex items-center gap-2">
								<Switch id="inviteOnly" bind:checked={inviteOnly} />
								<label for="inviteOnly" class="cursor-pointer text-sm font-medium"
									>Invite-only Market</label
								>
							</div>
							<p class="text-muted-foreground text-xs">Only invited users can participate</p>
						</div>
						{#if inviteOnly}
							<div class="space-y-2">
								<label for="initialInvites" class="text-sm font-medium"
									>Initial Invites (comma-separated Principal IDs)</label
								>
								<Textarea
									id="initialInvites"
									bind:value={initialInvites}
									placeholder="principal1, principal2..."
									rows={3}
								/>
							</div>
						{/if}
						<Button type="submit" disabled={isCreatingMarket} class="w-full">
							{#if isCreatingMarket}
								<Loader2 size={16} class="mr-2 animate-spin" />
								Creating...
							{:else}
								<Plus size={16} class="mr-2" />
								Create Market
							{/if}
						</Button>
					</form>
				</div>
			</Card>
		{:else if activeTab === 'grant'}
			<Card>
				<div class="p-6">
					<h3 class="mb-6 flex items-center gap-2 text-xl font-bold">
						<Coins size={20} />
						Grant Vici Coins
					</h3>
					<div class="mb-6 flex gap-3 rounded-lg bg-blue-50 p-4 text-blue-800">
						<Info size={20} class="shrink-0" />
						<p class="text-sm">This feature is not yet fully implemented in the backend.</p>
					</div>
					<form class="space-y-4">
						<div class="space-y-2">
							<label for="userPrincipal" class="text-sm font-medium">User Principal ID *</label>
							<Input
								id="userPrincipal"
								bind:value={userPrincipal}
								placeholder="Enter user's Principal ID"
								disabled
							/>
						</div>
						<div class="space-y-2">
							<label for="coinAmount" class="text-sm font-medium">Amount (Ꝟ) *</label>
							<Input
								id="coinAmount"
								type="number"
								bind:value={coinAmount}
								placeholder="1000"
								disabled
							/>
						</div>
						<Button disabled class="w-full">
							<Coins size={16} class="mr-2" />
							Grant Coins (Coming Soon)
						</Button>
					</form>
				</div>
			</Card>
		{:else if activeTab === 'admins'}
			<Card>
				<div class="space-y-6 p-6">
					<h3 class="flex items-center gap-2 text-xl font-bold">
						<Shield size={20} />
						Admin Management
					</h3>
					<div class="flex gap-3 rounded-lg bg-blue-50 p-4 text-blue-800">
						<Info size={20} class="shrink-0" />
						<p class="text-sm">Admin management features are coming in a future update.</p>
					</div>

					<div class="space-y-3">
						<h4 class="text-sm font-bold">Current Admins</h4>
						{#if isAdminListLoading}
							<div class="flex justify-center py-8">
								<Loader2 class="text-primary animate-spin" />
							</div>
						{:else if adminList.length > 0}
							<div class="space-y-2">
								{#each adminList as admin, index}
									<div
										class="flex items-center justify-between rounded-lg border border-slate-100 bg-slate-50 p-3"
									>
										<div class="flex items-center gap-3">
											{#if index === 0}<Crown size={16} class="text-yellow-500" />{/if}
											<code class="font-mono text-xs">{admin.toString()}</code>
											{#if index === 0}
												<Badge
													variant="outline"
													class="border-yellow-200 bg-yellow-50 text-yellow-700">Owner</Badge
												>
											{/if}
										</div>
									</div>
								{/each}
							</div>
						{:else}
							<p class="text-muted-foreground py-8 text-center text-sm">
								No admins found or feature not yet supported.
							</p>
						{/if}
					</div>
				</div>
			</Card>
		{/if}
	</div>
</div>

// old/frontend/src-react/pages/AdminPage.tsx
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
	AlertDialog,
	AlertDialogAction,
	AlertDialogCancel,
	AlertDialogContent,
	AlertDialogDescription,
	AlertDialogFooter,
	AlertDialogHeader,
	AlertDialogTitle,
	AlertDialogTrigger
} from '@/components/ui/alert-dialog';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { Principal } from '@icp-sdk/core/principal';
import {
	AlertTriangle,
	CheckCircle,
	Clock,
	Coins,
	Crown,
	Info,
	Lock,
	Plus,
	Shield,
	UserMinus
} from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { MarketSnapshot, MarketStatus } from '../backend';
import { useInternetIdentity } from '../hooks/useInternetIdentity';
import {
	useAddAdmin,
	useAdminList,
	useCreateMarket,
	useGetAllMarkets,
	useGrantViciCoins,
	useRemoveAdmin,
	useResolveMarket
} from '../hooks/useQueries';

export default function AdminPage() {
	const createMarket = useCreateMarket();
	const resolveMarket = useResolveMarket();
	const grantCoins = useGrantViciCoins();
	const { data: markets = [] } = useGetAllMarkets();
	const { data: adminList = [], isLoading: adminListLoading } = useAdminList();
	const addAdmin = useAddAdmin();
	const removeAdmin = useRemoveAdmin();
	const { identity } = useInternetIdentity();

	// Create Market Form
	const [title, setTitle] = useState('');
	const [description, setDescription] = useState('');
	const [categories, setCategories] = useState('');
	const [expirationDate, setExpirationDate] = useState('');
	const [inviteOnly, setInviteOnly] = useState(false);
	const [initialInvites, setInitialInvites] = useState('');

	// Grant Coins Form
	const [userPrincipal, setUserPrincipal] = useState('');
	const [coinAmount, setCoinAmount] = useState('');

	// Admin Management Form
	const [newAdminPrincipal, setNewAdminPrincipal] = useState('');

	// Market Resolution State
	const [selectedOutcomes, setSelectedOutcomes] = useState<
		Record<string, 'yes' | 'no' | 'canceled'>
	>({});

	// Determine if current user is the owner (first admin in the list)
	const currentUserPrincipal = identity?.getPrincipal().toString();
	const ownerPrincipal = adminList.length > 0 ? adminList[0].toString() : null;
	const isOwner = currentUserPrincipal === ownerPrincipal;

	const handleCreateMarket = async (e: React.FormEvent) => {
		e.preventDefault();

		if (!title || !description || !expirationDate) {
			toast.error('Please fill in all required fields');
			return;
		}

		try {
			const expiration = BigInt(new Date(expirationDate).getTime() * 1000000);
			const categoryArray = categories
				.split(',')
				.map((c) => c.trim())
				.filter(Boolean);

			let invitedUsersList: Principal[] = [];
			if (inviteOnly && initialInvites.trim()) {
				const invitePrincipals = initialInvites
					.split(',')
					.map((p) => p.trim())
					.filter(Boolean);

				try {
					invitedUsersList = invitePrincipals.map((p) => Principal.fromText(p));
				} catch (error) {
					toast.error('Invalid Principal ID in invites list');
					return;
				}
			}

			await createMarket.mutateAsync({
				title,
				description,
				categories: categoryArray,
				expiration,
				inviteOnly,
				invitedUsers: invitedUsersList
			});

			toast.success('Market created successfully');
			setTitle('');
			setDescription('');
			setCategories('');
			setExpirationDate('');
			setInviteOnly(false);
			setInitialInvites('');
		} catch (error: any) {
			toast.error(error.message || 'Failed to create market');
		}
	};

	const handleResolveMarket = async (marketId: bigint, outcome: 'yes' | 'no' | 'canceled') => {
		try {
			// Backend only supports YES (true) or NO (false)
			// CANCELED is not yet supported in the backend
			if (outcome === 'canceled') {
				toast.error('CANCELED outcome is not yet supported');
				return;
			}

			const booleanOutcome = outcome === 'yes';
			await resolveMarket.mutateAsync({ marketId, outcome: booleanOutcome });
			toast.success(`Market resolved as ${outcome.toUpperCase()}`);

			// Clear the selected outcome for this market
			setSelectedOutcomes((prev) => {
				const updated = { ...prev };
				delete updated[marketId.toString()];
				return updated;
			});
		} catch (error: any) {
			toast.error(error.message || 'Failed to resolve market');
		}
	};

	const handleGrantCoins = async (e: React.FormEvent) => {
		e.preventDefault();

		if (!userPrincipal || !coinAmount) {
			toast.error('Please fill in all fields');
			return;
		}

		try {
			const principal = Principal.fromText(userPrincipal);
			const amount = BigInt(parseInt(coinAmount));

			await grantCoins.mutateAsync({ user: principal, amount });
			toast.success(`Granted Ꝟ ${coinAmount} successfully`);
			setUserPrincipal('');
			setCoinAmount('');
		} catch (error: any) {
			toast.error(error.message || 'Failed to grant coins');
		}
	};

	const handleAddAdmin = async (e: React.FormEvent) => {
		e.preventDefault();

		if (!newAdminPrincipal.trim()) {
			toast.error('Please enter a Principal ID');
			return;
		}

		try {
			const principal = Principal.fromText(newAdminPrincipal.trim());

			// Check if already an admin
			if (adminList.some((admin) => admin.toString() === principal.toString())) {
				toast.error('This user is already an admin');
				return;
			}

			await addAdmin.mutateAsync(principal);
			setNewAdminPrincipal('');
		} catch (error: any) {
			if (error.message.includes('Invalid principal')) {
				toast.error('Invalid Principal ID format');
			} else {
				toast.error(error.message || 'Failed to add admin');
			}
		}
	};

	const handleRemoveAdmin = async (principal: Principal) => {
		try {
			await removeAdmin.mutateAsync(principal);
		} catch (error: any) {
			toast.error(error.message || 'Failed to remove admin');
		}
	};

	// Sort markets: expired unresolved first, then by expiry date
	const sortedMarkets = [...markets].sort((a, b) => {
		const now = Date.now() * 1000000; // Convert to nanoseconds
		const aExpired = Number(a.expiration) < now;
		const bExpired = Number(b.expiration) < now;
		const aResolved = a.status === MarketStatus.resolved;
		const bResolved = b.status === MarketStatus.resolved;

		// Expired unresolved markets first
		if (aExpired && !aResolved && (!bExpired || bResolved)) return -1;
		if (bExpired && !bResolved && (!aExpired || aResolved)) return 1;

		// Then sort by expiration date (closest first)
		return Number(a.expiration) - Number(b.expiration);
	});

	const isMarketExpired = (expiration: bigint): boolean => {
		const now = Date.now() * 1000000; // Convert to nanoseconds
		return Number(expiration) < now;
	};

	const formatExpirationDate = (expiration: bigint): string => {
		const date = new Date(Number(expiration) / 1000000);
		return date.toLocaleString();
	};

	const getOutcomeDisplay = (market: MarketSnapshot): string => {
		if (market.resolvedOutcome === undefined) return 'Not resolved';
		return market.resolvedOutcome ? 'YES' : 'NO';
	};

	return (
		<div className="container mx-auto px-4 py-8">
			<div className="space-y-8">
				{/* Header */}
				<div>
					<h1 className="text-foreground text-4xl font-bold">Admin Panel</h1>
					<p className="text-muted-foreground mt-2">Manage markets, users, and admins</p>
				</div>

				<Tabs defaultValue="resolve">
					<TabsList>
						<TabsTrigger value="resolve">Market Resolution</TabsTrigger>
						<TabsTrigger value="create">Create Market</TabsTrigger>
						<TabsTrigger value="grant">Grant Coins</TabsTrigger>
						<TabsTrigger value="admins">Admin Management</TabsTrigger>
					</TabsList>

					{/* Market Resolution Dashboard */}
					<TabsContent value="resolve" className="mt-6">
						<Card>
							<CardHeader>
								<CardTitle className="flex items-center gap-2">
									<CheckCircle className="h-5 w-5" />
									Market Resolution Dashboard
								</CardTitle>
								<p className="text-muted-foreground text-sm">
									Resolve market outcomes. Expired markets requiring urgent attention are
									highlighted.
								</p>
							</CardHeader>
							<CardContent>
								{sortedMarkets.length > 0 ? (
									<div className="space-y-3">
										{sortedMarkets.map((market) => {
											const expired = isMarketExpired(market.expiration);
											const resolved = market.status === MarketStatus.resolved;
											const urgent = expired && !resolved;
											const marketIdStr = market.id.toString();
											const selectedOutcome = selectedOutcomes[marketIdStr];

											return (
												<div
													key={marketIdStr}
													className={`rounded-lg border-2 p-4 transition-all ${
														urgent
															? 'border-destructive bg-destructive/5 shadow-md'
															: 'border-border bg-card'
													}`}
												>
													{/* Urgency Badge */}
													{urgent && (
														<div className="text-destructive mb-3 flex items-center gap-2">
															<AlertTriangle className="h-5 w-5" />
															<span className="text-sm font-semibold tracking-wide uppercase">
																Urgent: Expired & Unresolved
															</span>
														</div>
													)}

													<div className="space-y-3">
														{/* Market Info */}
														<div className="flex items-start justify-between gap-4">
															<div className="min-w-0 flex-1">
																<h3 className="text-foreground text-lg font-semibold">
																	{market.title}
																</h3>
																<p className="text-muted-foreground mt-1 line-clamp-2 text-sm">
																	{market.description}
																</p>
															</div>
														</div>

														{/* Status and Metadata */}
														<div className="flex flex-wrap items-center gap-2">
															{/* Status Badge */}
															{market.status === MarketStatus.open && (
																<Badge className="bg-chart-2">Open</Badge>
															)}
															{market.status === MarketStatus.closed && (
																<Badge variant="secondary">Closed</Badge>
															)}
															{market.status === MarketStatus.resolved && (
																<Badge className="bg-chart-1">Resolved</Badge>
															)}

															{/* Invite-only Badge */}
															{market.inviteOnly && (
																<Badge variant="outline" className="gap-1">
																	<Lock className="h-3 w-3" />
																	Invite-only
																</Badge>
															)}

															{/* Expiration Badge */}
															<Badge
																variant={expired ? 'destructive' : 'outline'}
																className="gap-1"
															>
																<Clock className="h-3 w-3" />
																{expired ? 'Expired' : 'Active'}
															</Badge>

															{/* Expiration Date */}
															<span className="text-muted-foreground text-xs">
																Expires: {formatExpirationDate(market.expiration)}
															</span>
														</div>

														{/* Resolution Section */}
														{resolved ? (
															<div className="border-border border-t pt-3">
																<div className="flex items-center gap-2">
																	<span className="text-muted-foreground text-sm font-medium">
																		Resolved Outcome:
																	</span>
																	<Badge
																		className={
																			market.resolvedOutcome ? 'bg-chart-2' : 'bg-destructive'
																		}
																	>
																		{getOutcomeDisplay(market)}
																	</Badge>
																</div>
															</div>
														) : (
															<div className="border-border space-y-3 border-t pt-3">
																<Label className="text-sm font-medium">Select Outcome:</Label>
																<RadioGroup
																	value={selectedOutcome || ''}
																	onValueChange={(value) => {
																		setSelectedOutcomes((prev) => ({
																			...prev,
																			[marketIdStr]: value as 'yes' | 'no' | 'canceled'
																		}));
																	}}
																	className="flex gap-4"
																>
																	<div className="flex items-center space-x-2">
																		<RadioGroupItem value="yes" id={`yes-${marketIdStr}`} />
																		<Label
																			htmlFor={`yes-${marketIdStr}`}
																			className="cursor-pointer font-normal"
																		>
																			YES
																		</Label>
																	</div>
																	<div className="flex items-center space-x-2">
																		<RadioGroupItem value="no" id={`no-${marketIdStr}`} />
																		<Label
																			htmlFor={`no-${marketIdStr}`}
																			className="cursor-pointer font-normal"
																		>
																			NO
																		</Label>
																	</div>
																	<div className="flex items-center space-x-2">
																		<RadioGroupItem
																			value="canceled"
																			id={`canceled-${marketIdStr}`}
																		/>
																		<Label
																			htmlFor={`canceled-${marketIdStr}`}
																			className="text-muted-foreground cursor-pointer font-normal"
																		>
																			CANCELED
																		</Label>
																	</div>
																</RadioGroup>

																<Button
																	size="sm"
																	onClick={() => handleResolveMarket(market.id, selectedOutcome)}
																	disabled={!selectedOutcome || resolveMarket.isPending}
																	className={urgent ? 'bg-destructive hover:bg-destructive/90' : ''}
																>
																	{resolveMarket.isPending ? (
																		'Resolving...'
																	) : (
																		<>
																			<CheckCircle className="mr-2 h-4 w-4" />
																			Resolve Market
																		</>
																	)}
																</Button>
															</div>
														)}
													</div>
												</div>
											);
										})}
									</div>
								) : (
									<div className="text-muted-foreground py-12 text-center">
										<p>No markets available</p>
									</div>
								)}
							</CardContent>
						</Card>
					</TabsContent>

					{/* Create Market */}
					<TabsContent value="create" className="mt-6">
						<Card>
							<CardHeader>
								<CardTitle className="flex items-center gap-2">
									<Plus className="h-5 w-5" />
									Create New Market
								</CardTitle>
							</CardHeader>
							<CardContent>
								<form onSubmit={handleCreateMarket} className="space-y-4">
									<div className="space-y-2">
										<Label htmlFor="title">Title *</Label>
										<Input
											id="title"
											value={title}
											onChange={(e) => setTitle(e.target.value)}
											placeholder="Will Bitcoin reach $100k by end of 2025?"
											required
										/>
									</div>

									<div className="space-y-2">
										<Label htmlFor="description">Description *</Label>
										<Textarea
											id="description"
											value={description}
											onChange={(e) => setDescription(e.target.value)}
											placeholder="Detailed description of the market and resolution criteria..."
											rows={4}
											required
										/>
									</div>

									<div className="space-y-2">
										<Label htmlFor="categories">Categories (comma-separated)</Label>
										<Input
											id="categories"
											value={categories}
											onChange={(e) => setCategories(e.target.value)}
											placeholder="Crypto, Finance, Technology"
										/>
									</div>

									<div className="space-y-2">
										<Label htmlFor="expiration">Expiration Date *</Label>
										<Input
											id="expiration"
											type="datetime-local"
											value={expirationDate}
											onChange={(e) => setExpirationDate(e.target.value)}
											required
										/>
									</div>

									<div className="space-y-2">
										<div className="flex items-center gap-2">
											<Switch
												id="inviteOnly"
												checked={inviteOnly}
												onCheckedChange={setInviteOnly}
											/>
											<Label htmlFor="inviteOnly" className="cursor-pointer">
												Invite-only Market
											</Label>
										</div>
										<p className="text-muted-foreground text-xs">
											Only invited users can participate in this market
										</p>
									</div>

									{inviteOnly && (
										<div className="space-y-2">
											<Label htmlFor="initialInvites">
												Initial Invites (comma-separated Principal IDs)
											</Label>
											<Textarea
												id="initialInvites"
												value={initialInvites}
												onChange={(e) => setInitialInvites(e.target.value)}
												placeholder="principal1, principal2, principal3..."
												rows={3}
											/>
										</div>
									)}

									<Button type="submit" disabled={createMarket.isPending} className="w-full">
										{createMarket.isPending ? (
											'Creating...'
										) : (
											<>
												<Plus className="mr-2 h-4 w-4" />
												Create Market
											</>
										)}
									</Button>
								</form>
							</CardContent>
						</Card>
					</TabsContent>

					{/* Grant Coins */}
					<TabsContent value="grant" className="mt-6">
						<Card>
							<CardHeader>
								<CardTitle className="flex items-center gap-2">
									<Coins className="h-5 w-5" />
									Grant Vici Coins
								</CardTitle>
							</CardHeader>
							<CardContent>
								<Alert className="mb-4">
									<Info className="h-4 w-4" />
									<AlertDescription>
										This feature is not yet implemented in the backend. It will be available in a
										future update.
									</AlertDescription>
								</Alert>
								<form onSubmit={handleGrantCoins} className="space-y-4">
									<div className="space-y-2">
										<Label htmlFor="userPrincipal">User Principal ID *</Label>
										<Input
											id="userPrincipal"
											value={userPrincipal}
											onChange={(e) => setUserPrincipal(e.target.value)}
											placeholder="Enter user's Principal ID"
											required
											disabled
										/>
									</div>

									<div className="space-y-2">
										<Label htmlFor="coinAmount">Amount (Ꝟ) *</Label>
										<Input
											id="coinAmount"
											type="number"
											min="1"
											value={coinAmount}
											onChange={(e) => setCoinAmount(e.target.value)}
											placeholder="1000"
											required
											disabled
										/>
									</div>

									<Button type="submit" disabled className="w-full">
										<Coins className="mr-2 h-4 w-4" />
										Grant Coins (Coming Soon)
									</Button>
								</form>
							</CardContent>
						</Card>
					</TabsContent>

					{/* Admin Management */}
					<TabsContent value="admins" className="mt-6">
						<Card>
							<CardHeader>
								<CardTitle className="flex items-center gap-2">
									<Shield className="h-5 w-5" />
									Admin Management
								</CardTitle>
								<p className="text-muted-foreground text-sm">
									View and manage platform administrators
								</p>
							</CardHeader>
							<CardContent className="space-y-6">
								<Alert>
									<Info className="h-4 w-4" />
									<AlertDescription>
										Admin management features are not yet fully implemented in the backend. This
										interface will be functional in a future update.
									</AlertDescription>
								</Alert>

								{/* Admin List */}
								<div className="space-y-3">
									<h3 className="text-foreground text-sm font-semibold">Current Admins</h3>
									{adminListLoading ? (
										<div className="text-muted-foreground py-8 text-center">
											<p>Loading admin list...</p>
										</div>
									) : adminList.length > 0 ? (
										<div className="space-y-2">
											{adminList.map((admin, index) => {
												const adminStr = admin.toString();
												const isAdminOwner = index === 0;
												const isCurrentUser = adminStr === currentUserPrincipal;

												return (
													<div
														key={adminStr}
														className="bg-card flex items-center justify-between rounded-lg border p-3"
													>
														<div className="flex min-w-0 flex-1 items-center gap-3">
															{isAdminOwner && (
																<Crown className="h-5 w-5 flex-shrink-0 text-yellow-500" />
															)}
															<div className="min-w-0 flex-1">
																<div className="flex flex-wrap items-center gap-2">
																	<code className="bg-muted rounded px-2 py-1 font-mono text-xs break-all">
																		{adminStr}
																	</code>
																	{isAdminOwner && (
																		<Badge
																			variant="outline"
																			className="border-yellow-600 text-yellow-600"
																		>
																			Owner
																		</Badge>
																	)}
																	{isCurrentUser && <Badge variant="secondary">You</Badge>}
																</div>
															</div>
														</div>
														{isOwner && !isAdminOwner && (
															<AlertDialog>
																<AlertDialogTrigger asChild>
																	<Button
																		variant="ghost"
																		size="sm"
																		className="text-destructive hover:text-destructive hover:bg-destructive/10"
																		disabled
																	>
																		<UserMinus className="h-4 w-4" />
																	</Button>
																</AlertDialogTrigger>
																<AlertDialogContent>
																	<AlertDialogHeader>
																		<AlertDialogTitle>Remove Admin</AlertDialogTitle>
																		<AlertDialogDescription>
																			Are you sure you want to remove this admin? They will lose all
																			admin privileges.
																		</AlertDialogDescription>
																	</AlertDialogHeader>
																	<AlertDialogFooter>
																		<AlertDialogCancel>Cancel</AlertDialogCancel>
																		<AlertDialogAction
																			onClick={() => handleRemoveAdmin(admin)}
																			className="bg-destructive hover:bg-destructive/90"
																		>
																			Remove
																		</AlertDialogAction>
																	</AlertDialogFooter>
																</AlertDialogContent>
															</AlertDialog>
														)}
													</div>
												);
											})}
										</div>
									) : (
										<div className="text-muted-foreground py-8 text-center">
											<p>No admins found (feature not yet implemented)</p>
										</div>
									)}
								</div>

								{/* Add Admin Form - Only visible to owner */}
								{isOwner && (
									<div className="border-border border-t pt-6">
										<h3 className="text-foreground mb-3 text-sm font-semibold">Add New Admin</h3>
										<form onSubmit={handleAddAdmin} className="space-y-4">
											<div className="space-y-2">
												<Label htmlFor="newAdminPrincipal">Principal ID *</Label>
												<Input
													id="newAdminPrincipal"
													value={newAdminPrincipal}
													onChange={(e) => setNewAdminPrincipal(e.target.value)}
													placeholder="Enter Principal ID to grant admin access"
													required
													disabled
												/>
												<p className="text-muted-foreground text-xs">
													The user will be able to resolve markets, create markets, and grant coins
												</p>
											</div>

											<Button type="submit" disabled className="w-full">
												<Shield className="mr-2 h-4 w-4" />
												Add Admin (Coming Soon)
											</Button>
										</form>
									</div>
								)}

								{!isOwner && adminList.length > 0 && (
									<div className="border-border border-t pt-6">
										<div className="text-muted-foreground py-4 text-center text-sm">
											<p>Only the owner can add or remove admins</p>
										</div>
									</div>
								)}
							</CardContent>
						</Card>
					</TabsContent>
				</Tabs>
			</div>
		</div>
	);
}
