// old/frontend/src-react/components/MarketDiscussion.tsx
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { Skeleton } from '@/components/ui/skeleton';
import { Textarea } from '@/components/ui/textarea';
import { EyeOff, LogIn, MessageSquare, Send } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { useInternetIdentity } from '../hooks/useInternetIdentity';
import {
	useCreateComment,
	useGetCallerUserProfile,
	useGetMarketComments,
	useIsCallerAdmin,
	useModerateComment
} from '../hooks/useQueries';

interface MarketDiscussionProps {
	marketId: bigint;
}

export default function MarketDiscussion({ marketId }: MarketDiscussionProps) {
	const { data: comments = [], isLoading } = useGetMarketComments(marketId);
	const { data: isAdmin = false } = useIsCallerAdmin();
	const { data: userProfile } = useGetCallerUserProfile();
	const { identity, login } = useInternetIdentity();
	const createComment = useCreateComment();
	const moderateComment = useModerateComment();
	const [commentText, setCommentText] = useState('');

	const isAuthenticated = !!identity;

	const handleLoginPrompt = async () => {
		try {
			await login();
		} catch (error: any) {
			console.error('Login error:', error);
			toast.error('Failed to login. Please try again.');
		}
	};

	const handlePostComment = async () => {
		if (!commentText.trim()) {
			toast.error('Please enter a comment');
			return;
		}

		try {
			await createComment.mutateAsync({
				marketId,
				content: commentText.trim()
			});
			toast.success('Comment posted successfully');
			setCommentText('');
		} catch (error: any) {
			toast.error(error.message || 'Failed to post comment');
		}
	};

	const handleModerate = async (commentId: bigint) => {
		try {
			await moderateComment.mutateAsync({
				marketId,
				commentId
			});
			toast.success('Comment hidden');
		} catch (error: any) {
			toast.error(error.message || 'Failed to moderate comment');
		}
	};

	const formatDate = (timestamp: bigint) => {
		const date = new Date(Number(timestamp) / 1000000);
		const now = new Date();
		const diffMs = now.getTime() - date.getTime();
		const diffMins = Math.floor(diffMs / 60000);
		const diffHours = Math.floor(diffMs / 3600000);
		const diffDays = Math.floor(diffMs / 86400000);

		if (diffMins < 1) return 'Just now';
		if (diffMins < 60) return `${diffMins}m ago`;
		if (diffHours < 24) return `${diffHours}h ago`;
		if (diffDays < 7) return `${diffDays}d ago`;
		return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
	};

	const getInitials = (nickname: string) => {
		return nickname
			.split(' ')
			.map((n) => n[0])
			.join('')
			.toUpperCase()
			.slice(0, 2);
	};

	if (isLoading) {
		return (
			<div className="space-y-4">
				<Skeleton className="h-24 w-full" />
				<Skeleton className="h-20 w-full" />
				<Skeleton className="h-20 w-full" />
			</div>
		);
	}

	return (
		<div className="space-y-4">
			{/* Comment Input */}
			{isAuthenticated ? (
				<div className="space-y-3">
					<Textarea
						placeholder="Share your thoughts on this market..."
						value={commentText}
						onChange={(e) => setCommentText(e.target.value)}
						rows={3}
						className="resize-none"
					/>
					<div className="flex justify-end">
						<Button
							onClick={handlePostComment}
							disabled={createComment.isPending || !commentText.trim()}
							size="sm"
						>
							{createComment.isPending ? (
								'Posting...'
							) : (
								<>
									<Send className="mr-2 h-4 w-4" />
									Post Comment
								</>
							)}
						</Button>
					</div>
				</div>
			) : (
				<div className="bg-accent/20 border-border space-y-3 rounded-lg border p-6 text-center">
					<LogIn className="text-muted-foreground mx-auto h-10 w-10" />
					<div>
						<p className="text-foreground mb-1 text-sm font-medium">Login to Join the Discussion</p>
						<p className="text-muted-foreground mb-4 text-xs">
							Sign in to share your thoughts and insights
						</p>
					</div>
					<Button onClick={handleLoginPrompt} size="sm">
						<LogIn className="mr-2 h-4 w-4" />
						Login to Comment
					</Button>
				</div>
			)}

			<Separator />

			{/* Comments List */}
			{comments.length === 0 ? (
				<div className="text-muted-foreground py-8 text-center">
					<MessageSquare className="mx-auto mb-3 h-12 w-12 opacity-50" />
					<p>No comments yet. Start the conversation!</p>
				</div>
			) : (
				<ScrollArea className="h-[400px] pr-4">
					<div className="space-y-4">
						{comments.map((comment) => {
							const isCurrentUser = identity?.getPrincipal().toString() === comment.user.toString();

							return (
								<div
									key={comment.id.toString()}
									className={`rounded-lg border p-4 ${
										comment.isHidden ? 'bg-muted/50 border-muted' : 'bg-card border-border'
									}`}
								>
									<div className="flex gap-3">
										<Avatar className="h-10 w-10">
											<AvatarFallback className="bg-primary/10 text-primary text-sm">
												{getInitials(comment.user.toString().slice(0, 5))}
											</AvatarFallback>
										</Avatar>
										<div className="flex-1 space-y-2">
											<div className="flex items-center justify-between">
												<div className="flex items-center gap-2">
													<span className="text-sm font-medium">
														{isCurrentUser ? userProfile?.nickname || 'You' : 'Anonymous'}
													</span>
													<span className="text-muted-foreground text-xs">
														{formatDate(comment.createdAt)}
													</span>
												</div>
												{isAdmin && !comment.isHidden && (
													<Button
														variant="ghost"
														size="sm"
														onClick={() => handleModerate(comment.id)}
														disabled={moderateComment.isPending}
													>
														<EyeOff className="mr-1 h-4 w-4" />
														Hide
													</Button>
												)}
											</div>
											<p
												className={`text-sm ${comment.isHidden ? 'text-muted-foreground italic' : ''}`}
											>
												{comment.isHidden && !isAdmin
													? '[Comment hidden by moderator]'
													: comment.content}
											</p>
										</div>
									</div>
								</div>
							);
						})}
					</div>
				</ScrollArea>
			)}
		</div>
	);
}

// src/lib/components/social/MarketDiscussion.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import LoadingSpinner from '$lib/components/ui/LoadingSpinner.svelte';
	import { activityService } from '$lib/services/activity.services';
	import { discussionService, type Comment } from '$lib/services/discussion.services';
	import { getProfile } from '$lib/services/profile.services';
	import type { UserProfile } from '$lib/types/profile';
	import { ActivityType } from '$lib/types/social';

	interface Props {
		marketId: string;
		userPrincipal: string;
	}

	const { marketId, userPrincipal }: Props = $props();

	let comments: (Comment & { key: string })[] = $state([]);
	const profiles: Map<string, UserProfile> = $state(new Map());
	let newComment = $state('');
	let loading = $state(true);
	let posting = $state(false);

	onMount(async () => {
		await loadComments();
	});

	const loadComments = async () => {
		loading = true;
		try {
			comments = (await discussionService.getMarketComments(marketId)) ;

			for (const comment of comments) {
				if (!profiles.has(comment.user)) {
					const profile = await getProfile(comment.user);
					if (profile) {
						profiles.set(comment.user, profile);
					}
				}
			}
		} finally {
			loading = false;
		}
	};

	const handlePostComment = async () => {
		if (!newComment.trim() || posting) {
			return;
		}
		posting = true;
		try {
			await discussionService.addComment({
				marketId,
				user: userPrincipal,
				content: newComment.trim()
			});

			await activityService.logActivity({
				type: ActivityType.COMMENT,
				user: userPrincipal,
				marketId,
				title: `New comment on market`,
				details: newComment.trim().slice(0, 50) + (newComment.length > 50 ? '...' : '')
			});

			newComment = '';
			await loadComments();
		} finally {
			posting = false;
		}
	};
</script>

<div class="flex flex-col gap-6">
	<!-- Input -->
	<div class="glassmorphism rounded-2xl p-4">
		<textarea
			class="border-border bg-background/50 focus:ring-primary/50 w-full resize-none rounded-xl border p-4 text-sm focus:ring-2 focus:outline-none"
			placeholder="Share your thoughts..."
			rows="3"
			bind:value={newComment}
		></textarea>
		<div class="mt-3 flex justify-end">
			<Button disabled={!newComment.trim() || posting} onclick={handlePostComment}>
				{posting ? 'Posting...' : 'Post Comment'}
			</Button>
		</div>
	</div>

	<!-- List -->
	<div class="flex flex-col gap-4">
		{#if loading}
			<div class="flex justify-center py-8">
				<LoadingSpinner />
			</div>
		{:else if comments.length === 0}
			<div class="py-12 text-center opacity-40">
				<p class="text-sm italic">No comments yet. Be the first to start the discussion!</p>
			</div>
		{:else}
			{#each comments as comment (comment.key)}
				{@const profile = profiles.get(comment.user)}
				<div
					class="bg-card/20 border-border/50 animate-in fade-in slide-in-from-bottom-2 flex gap-4 rounded-2xl border p-4 duration-300"
				>
					<div class="bg-muted h-10 w-10 shrink-0 rounded-full">
						{#if profile?.avatar}
							<img class="h-full w-full rounded-full object-cover" alt="" src={profile.avatar} />
						{:else}
							<div class="flex h-full w-full items-center justify-center text-xs font-bold">
								{profile?.nickname?.[0] ?? '?'}
							</div>
						{/if}
					</div>
					<div class="flex-1 overflow-hidden">
						<div class="mb-1 flex items-center gap-2">
							<span class="text-sm font-bold">{profile?.nickname ?? 'Anonymous'}</span>
							<span class="text-muted-foreground text-[10px] opacity-50">
								{new Date(comment.timestamp).toLocaleString()}
							</span>
						</div>
						<p class="text-sm leading-relaxed whitespace-pre-wrap">{comment.content}</p>
					</div>
				</div>
			{/each}
		{/if}
	</div>
</div>

<style lang="postcss">
	.glassmorphism {
		background: rgba(255, 255, 255, 0.03);
		backdrop-filter: blur(10px);
		border: 1px solid rgba(255, 255, 255, 0.05);
	}
</style>
