// old/build-template/src/frontend/src/components/ui/avatar.tsx
'use client';

import * as AvatarPrimitive from '@radix-ui/react-avatar';
import * as React from 'react';

import { cn } from '@/lib/utils';

function Avatar({ className, ...props }: React.ComponentProps<typeof AvatarPrimitive.Root>) {
	return (
		<AvatarPrimitive.Root
			data-slot="avatar"
			className={cn('relative flex size-8 shrink-0 overflow-hidden rounded-full', className)}
			{...props}
		/>
	);
}

function AvatarImage({ className, ...props }: React.ComponentProps<typeof AvatarPrimitive.Image>) {
	return (
		<AvatarPrimitive.Image
			data-slot="avatar-image"
			className={cn('aspect-square size-full', className)}
			{...props}
		/>
	);
}

function AvatarFallback({
	className,
	...props
}: React.ComponentProps<typeof AvatarPrimitive.Fallback>) {
	return (
		<AvatarPrimitive.Fallback
			data-slot="avatar-fallback"
			className={cn('bg-muted flex size-full items-center justify-center rounded-full', className)}
			{...props}
		/>
	);
}

export { Avatar, AvatarFallback, AvatarImage };

// old/frontend/src/components/ui/Avatar.svelte
<script lang="ts">
	import { cn } from '@/lib/utils';

	export let src: string | undefined = undefined;
	export let alt: string | undefined = undefined;
	export let fallback: string = 'U';
	export let className: string = '';

	let imageLoaded = false;
	let imageError = false;

	$: showFallback = !src || imageError;
</script>

<div class={cn('relative flex size-10 shrink-0 overflow-hidden rounded-full', className)}>
	{#if src && !imageError}
		<img
			{src}
			{alt}
			class="aspect-square size-full"
			on:load={() => (imageLoaded = true)}
			on:error={() => (imageError = true)}
		/>
	{/if}

	{#if showFallback}
		<div
			class="bg-muted flex size-full items-center justify-center rounded-full bg-slate-200 font-medium text-slate-600"
		>
			{fallback}
		</div>
	{/if}
</div>
