// old/frontend/src-react/App.tsx
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from 'next-themes';
import { useState } from 'react';
import AccessDeniedScreen from './components/AccessDeniedScreen';
import Footer from './components/Footer';
import Header from './components/Header';
import ProfileSetupModal from './components/ProfileSetupModal';
import { useInternetIdentity } from './hooks/useInternetIdentity';
import { useGetCallerUserProfile, useIsCallerAdmin } from './hooks/useQueries';
import AdminPage from './pages/AdminPage';
import HomePage from './pages/HomePage';
import LeaderboardPage from './pages/LeaderboardPage';
import LearnPage from './pages/LearnPage';
import MarketDetailPage from './pages/MarketDetailPage';
import MarketsPage from './pages/MarketsPage';
import PortfolioPage from './pages/PortfolioPage';
import ProfilePage from './pages/ProfilePage';
import RushPage from './pages/RushPage';
import WalletPage from './pages/WalletPage';

export type Page =
	| 'home'
	| 'markets'
	| 'market-detail'
	| 'portfolio'
	| 'leaderboard'
	| 'learn'
	| 'profile'
	| 'admin'
	| 'rush'
	| 'wallet';

export default function App() {
	const { identity } = useInternetIdentity();
	const { data: userProfile, isLoading: profileLoading, isFetched } = useGetCallerUserProfile();
	const { data: isAdmin } = useIsCallerAdmin();
	const [currentPage, setCurrentPage] = useState<Page>('home');
	const [selectedMarketId, setSelectedMarketId] = useState<bigint | null>(null);

	const isAuthenticated = !!identity;
	const showProfileSetup = isAuthenticated && !profileLoading && isFetched && userProfile === null;

	// Navigate to market detail
	const navigateToMarket = (marketId: bigint) => {
		setSelectedMarketId(marketId);
		setCurrentPage('market-detail');
	};

	// Navigate back from market detail
	const navigateBack = () => {
		setCurrentPage('markets');
		setSelectedMarketId(null);
	};

	// Show access denied for non-authenticated users trying to access protected pages
	if (
		!isAuthenticated &&
		['portfolio', 'profile', 'admin', 'rush', 'wallet'].includes(currentPage)
	) {
		return (
			<ThemeProvider attribute="class" defaultTheme="light" enableSystem>
				<div className="bg-background flex min-h-screen flex-col">
					<Header currentPage={currentPage} onNavigate={setCurrentPage} />
					<AccessDeniedScreen />
					<Footer />
					<Toaster />
				</div>
			</ThemeProvider>
		);
	}

	return (
		<ThemeProvider attribute="class" defaultTheme="light" enableSystem>
			<div className="bg-background flex min-h-screen flex-col">
				<Header currentPage={currentPage} onNavigate={setCurrentPage} />

				<main className="flex-1">
					{currentPage === 'home' && <HomePage onViewMarket={navigateToMarket} />}
					{currentPage === 'markets' && <MarketsPage onViewMarket={navigateToMarket} />}
					{currentPage === 'market-detail' && selectedMarketId && (
						<MarketDetailPage marketId={selectedMarketId} onBack={navigateBack} />
					)}
					{currentPage === 'portfolio' && <PortfolioPage onViewMarket={navigateToMarket} />}
					{currentPage === 'leaderboard' && <LeaderboardPage />}
					{currentPage === 'learn' && <LearnPage onNavigate={setCurrentPage} />}
					{currentPage === 'profile' && <ProfilePage />}
					{currentPage === 'admin' && isAdmin && <AdminPage />}
					{currentPage === 'rush' && <RushPage onNavigate={setCurrentPage} />}
					{currentPage === 'wallet' && <WalletPage />}
				</main>

				<Footer />

				{showProfileSetup && <ProfileSetupModal />}
				<Toaster />
			</div>
		</ThemeProvider>
	);
}

// old/frontend/src/App.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { auth } from './stores/auth';
	import { userProfile, isAdmin } from './stores/profile';
	import { Toaster } from 'sonner';
	import Header from './components/Header.svelte';
	import Footer from './components/Footer.svelte';
	import HomePage from './pages/HomePage.svelte';
	import MarketsPage from './pages/MarketsPage.svelte';
	import MarketDetailPage from './pages/MarketDetailPage.svelte';
	import PortfolioPage from './pages/PortfolioPage.svelte';
	import LeaderboardPage from './pages/LeaderboardPage.svelte';
	import LearnPage from './pages/LearnPage.svelte';
	import ProfilePage from './pages/ProfilePage.svelte';
	import AdminPage from './pages/AdminPage.svelte';
	import RushPage from './pages/RushPage.svelte';
	import WalletPage from './pages/WalletPage.svelte';
	import ProfileSetupModal from './components/ProfileSetupModal.svelte';
	import AccessDeniedScreen from './components/AccessDeniedScreen.svelte';

	type Page =
		| 'home'
		| 'markets'
		| 'market-detail'
		| 'portfolio'
		| 'leaderboard'
		| 'learn'
		| 'profile'
		| 'admin'
		| 'rush'
		| 'wallet';

	let currentPage: Page = 'home';
	let selectedMarketId: bigint | null = null;

	$: isAuthenticated =
		$auth.loginStatus === 'success' ||
		(!!$auth.identity && !$auth.identity.getPrincipal().isAnonymous());
	$: showsProfileSetup =
		isAuthenticated &&
		!$userProfile.isLoading &&
		$userProfile.isFetched &&
		$userProfile.profile === null;

	const navigateToMarket = (marketId: bigint) => {
		selectedMarketId = marketId;
		currentPage = 'market-detail';
	};

	const navigateBack = () => {
		currentPage = 'markets';
		selectedMarketId = null;
	};

	const handleNavigate = (page: string) => {
		currentPage = page as Page;
		if (page !== 'market-detail') {
			selectedMarketId = null;
		}
	};

	$: isProtectedRoute = ['portfolio', 'profile', 'admin', 'rush', 'wallet'].includes(currentPage);
	$: showAccessDenied = !isAuthenticated && isProtectedRoute;
</script>

<div class="flex min-h-screen flex-col bg-slate-50 font-sans text-slate-900">
	<Header {currentPage} onNavigate={handleNavigate} />

	<main class="flex flex-1 flex-col">
		{#if showAccessDenied}
			<AccessDeniedScreen />
		{:else if currentPage === 'home'}
			<HomePage onViewMarket={navigateToMarket} />
		{:else if currentPage === 'markets'}
			<MarketsPage onViewMarket={navigateToMarket} />
		{:else if currentPage === 'market-detail' && selectedMarketId}
			<MarketDetailPage marketId={selectedMarketId} onBack={navigateBack} />
		{:else if currentPage === 'portfolio'}
			<PortfolioPage onViewMarket={navigateToMarket} />
		{:else if currentPage === 'leaderboard'}
			<LeaderboardPage />
		{:else if currentPage === 'learn'}
			<LearnPage onNavigate={handleNavigate} />
		{:else if currentPage === 'profile'}
			<ProfilePage />
		{:else if currentPage === 'admin' && $isAdmin}
			<AdminPage />
		{:else if currentPage === 'rush'}
			<RushPage onNavigate={handleNavigate} />
		{:else if currentPage === 'wallet'}
			<WalletPage />
		{/if}
	</main>

	<Footer />

	{#if showsProfileSetup}
		<ProfileSetupModal />
	{/if}

	<Toaster position="top-right" richColors />
</div>

<style>
	:global(:root) {
		--primary: 15 23 42;
		--primary-foreground: 248 250 252;
	}

	:global(body) {
		background-color: rgb(248, 250, 252);
		color: rgb(15, 23, 42);
		-webkit-font-smoothing: antialiased;
		-moz-osx-font-smoothing: grayscale;
	}
</style>
