// old/frontend/src/pages/WalletPage.svelte
<script lang="ts">
	import { wallet } from '../stores/wallet';
	import Card from '../components/ui/Card.svelte';
	import { Wallet, TrendingUp, TrendingDown, ArrowUpRight, ArrowDownLeft } from 'lucide-svelte';
	import SendTokenForm from '../components/SendTokenForm.svelte';
	import ReceiveTokenPanel from '../components/ReceiveTokenPanel.svelte';

	let activeTab = 'send';

	const formatBalance = (amount: bigint | null | undefined) => {
		if (amount === null || amount === undefined) return '0.00';
		const value = Number(amount) / 100_000_000;
		return value.toLocaleString(undefined, {
			minimumFractionDigits: 2,
			maximumFractionDigits: 8
		});
	};
</script>

<div class="container mx-auto max-w-6xl px-4 py-8">
	<div class="space-y-6">
		<!-- Header -->
		<div class="flex items-center gap-3">
			<div class="bg-primary/10 rounded-full p-3">
				<Wallet size={24} class="text-primary" />
			</div>
			<div>
				<h1 class="text-3xl font-bold">Wallet</h1>
				<p class="text-muted-foreground">Manage your ICP and ckUSDC tokens</p>
			</div>
		</div>

		<!-- Balance Cards -->
		<div class="grid gap-6 md:grid-cols-2">
			<!-- ICP Balance -->
			<Card>
				<div class="space-y-4 p-6">
					<div class="flex items-center justify-between">
						<h3 class="font-semibold">ICP Balance</h3>
						<TrendingUp size={20} class="text-primary" />
					</div>
					<p class="text-muted-foreground text-sm">Internet Computer Protocol</p>
					{#if $wallet.isLoading}
						<div class="h-10 animate-pulse rounded bg-slate-100"></div>
					{:else}
						<div class="space-y-2">
							<p class="text-4xl font-bold">
								{formatBalance($wallet.balance?.icp)}
							</p>
							<p class="text-muted-foreground text-sm">ICP</p>
						</div>
					{/if}
				</div>
			</Card>

			<!-- ckUSDC Balance -->
			<Card>
				<div class="space-y-4 p-6">
					<div class="flex items-center justify-between">
						<h3 class="font-semibold">ckUSDC Balance</h3>
						<TrendingDown size={20} class="text-primary" />
					</div>
					<p class="text-muted-foreground text-sm">Chain-Key USD Coin</p>
					{#if $wallet.isLoading}
						<div class="h-10 animate-pulse rounded bg-slate-100"></div>
					{:else}
						<div class="space-y-2">
							<p class="text-4xl font-bold">
								{formatBalance($wallet.balance?.ckUSDC)}
							</p>
							<p class="text-muted-foreground text-sm">ckUSDC</p>
						</div>
					{/if}
				</div>
			</Card>
		</div>

		<!-- Send/Receive Tabs -->
		<Card>
			<div class="space-y-6 p-6">
				<div class="space-y-1">
					<h3 class="text-lg font-semibold">Transactions</h3>
					<p class="text-muted-foreground text-sm">Send or receive tokens</p>
				</div>

				<div
					class="bg-muted text-muted-foreground inline-flex h-10 w-full items-center justify-center rounded-md bg-slate-100 p-1"
				>
					<button
						class="inline-flex flex-1 items-center justify-center rounded-sm px-3 py-1.5 text-sm font-medium whitespace-nowrap transition-all {activeTab ===
						'send'
							? 'text-foreground bg-white shadow-sm'
							: 'hover:bg-slate-200'}"
						on:click={() => (activeTab = 'send')}
					>
						<ArrowUpRight size={16} class="mr-2" />
						Send
					</button>
					<button
						class="inline-flex flex-1 items-center justify-center rounded-sm px-3 py-1.5 text-sm font-medium whitespace-nowrap transition-all {activeTab ===
						'receive'
							? 'text-foreground bg-white shadow-sm'
							: 'hover:bg-slate-200'}"
						on:click={() => (activeTab = 'receive')}
					>
						<ArrowDownLeft size={16} class="mr-2" />
						Receive
					</button>
				</div>

				<div class="mt-6">
					{#if activeTab === 'send'}
						<SendTokenForm currentBalance={$wallet.balance || undefined} />
					{:else}
						<ReceiveTokenPanel />
					{/if}
				</div>
			</div>
		</Card>

		<!-- Info Card -->
		<Card className="bg-slate-50">
			<div class="text-muted-foreground space-y-2 p-6 text-sm">
				<h3 class="text-foreground text-lg font-semibold">About IC Wallet</h3>
				<p>
					This wallet allows you to manage ICP (Internet Computer Protocol) and ckUSDC (Chain-Key
					USD Coin) tokens on the Internet Computer blockchain.
				</p>
				<p>
					<strong>Note:</strong> This is a demonstration wallet. In production, transactions would interact
					with the ICP Ledger and ckUSDC Ledger canisters via inter-canister calls.
				</p>
			</div>
		</Card>
	</div>
</div>

// old_app/vici-prediction-market-application/frontend/src/pages/WalletPage.tsx
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ArrowDownLeft, ArrowUpRight, TrendingDown, TrendingUp, Wallet } from 'lucide-react';
import ReceiveTokenPanel from '../components/ReceiveTokenPanel';
import SendTokenForm from '../components/SendTokenForm';
import { useGetWalletBalance } from '../hooks/useQueries';

export default function WalletPage() {
	const { data: walletBalance, isLoading, error } = useGetWalletBalance();

	const formatBalance = (amount: bigint | undefined) => {
		if (amount === undefined) return '0.00';
		// Convert from smallest unit (e8s for ICP, similar for ckUSDC)
		const value = Number(amount) / 100_000_000;
		return value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 8 });
	};

	return (
		<div className="container mx-auto px-4 py-8 max-w-6xl">
			<div className="space-y-6">
				{/* Header */}
				<div className="flex items-center gap-3">
					<div className="p-3 rounded-full bg-primary/10">
						<Wallet className="h-6 w-6 text-primary" />
					</div>
					<div>
						<h1 className="text-3xl font-bold">Wallet</h1>
						<p className="text-muted-foreground">Manage your ICP and ckUSDC tokens</p>
					</div>
				</div>

				{/* Balance Cards */}
				<div className="grid md:grid-cols-2 gap-6">
					{/* ICP Balance */}
					<Card>
						<CardHeader>
							<CardTitle className="flex items-center justify-between">
								<span>ICP Balance</span>
								<TrendingUp className="h-5 w-5 text-primary" />
							</CardTitle>
							<CardDescription>Internet Computer Protocol</CardDescription>
						</CardHeader>
						<CardContent>
							{isLoading ? (
								<Skeleton className="h-12 w-full" />
							) : error ? (
								<p className="text-destructive text-sm">Failed to load balance</p>
							) : (
								<div className="space-y-2">
									<p className="text-4xl font-bold">{formatBalance(walletBalance?.icp)}</p>
									<p className="text-sm text-muted-foreground">ICP</p>
								</div>
							)}
						</CardContent>
					</Card>

					{/* ckUSDC Balance */}
					<Card>
						<CardHeader>
							<CardTitle className="flex items-center justify-between">
								<span>ckUSDC Balance</span>
								<TrendingDown className="h-5 w-5 text-primary" />
							</CardTitle>
							<CardDescription>Chain-Key USD Coin</CardDescription>
						</CardHeader>
						<CardContent>
							{isLoading ? (
								<Skeleton className="h-12 w-full" />
							) : error ? (
								<p className="text-destructive text-sm">Failed to load balance</p>
							) : (
								<div className="space-y-2">
									<p className="text-4xl font-bold">{formatBalance(walletBalance?.ckUSDC)}</p>
									<p className="text-sm text-muted-foreground">ckUSDC</p>
								</div>
							)}
						</CardContent>
					</Card>
				</div>

				{/* Send/Receive Tabs */}
				<Card>
					<CardHeader>
						<CardTitle>Transactions</CardTitle>
						<CardDescription>Send or receive tokens</CardDescription>
					</CardHeader>
					<CardContent>
						<Tabs defaultValue="send" className="w-full">
							<TabsList className="grid w-full grid-cols-2">
								<TabsTrigger value="send" className="flex items-center gap-2">
									<ArrowUpRight className="h-4 w-4" />
									Send
								</TabsTrigger>
								<TabsTrigger value="receive" className="flex items-center gap-2">
									<ArrowDownLeft className="h-4 w-4" />
									Receive
								</TabsTrigger>
							</TabsList>
							<TabsContent value="send" className="mt-6">
								<SendTokenForm currentBalance={walletBalance || undefined} />
							</TabsContent>
							<TabsContent value="receive" className="mt-6">
								<ReceiveTokenPanel />
							</TabsContent>
						</Tabs>
					</CardContent>
				</Card>

				{/* Info Card */}
				<Card className="bg-muted/50">
					<CardHeader>
						<CardTitle className="text-lg">About IC Wallet</CardTitle>
					</CardHeader>
					<CardContent className="space-y-2 text-sm text-muted-foreground">
						<p>
							This wallet allows you to manage ICP (Internet Computer Protocol) and ckUSDC
							(Chain-Key USD Coin) tokens on the Internet Computer blockchain.
						</p>
						<p>
							<strong>Note:</strong> This is a demonstration wallet. In production, transactions
							would interact with the ICP Ledger and ckUSDC Ledger canisters via inter-canister
							calls.
						</p>
					</CardContent>
				</Card>
			</div>
		</div>
	);
}
